export const ERROR_CODES = {
  IP_BLOCKED: 'IP_BLOCKED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_QR: 'INVALID_QR',
  FOOD_ALREADY_USED: 'FOOD_ALREADY_USED',
  ENTRY_ALREADY_DONE: 'ENTRY_ALREADY_DONE',
  UNAUTHORIZED: 'UNAUTHORIZED',
};
